/**
 * Checks if a transaction represents metadata, balance summaries, or page totals.
 */
export function isMetadataTransaction(tx: any): boolean {
  if (!tx) return true;

  // Resolve description
  const desc = (tx.description || '').toLowerCase().trim();
  const hasDate = !!tx.transaction_date;
  const amtVal = tx.amount_in_base_currency !== null && tx.amount_in_base_currency !== undefined
    ? Number(tx.amount_in_base_currency)
    : Number(tx.amount);
  const hasAmount = !isNaN(amtVal);

  // Check for blank/invalid transaction rows
  if (!desc && !hasDate && !hasAmount) {
    return true; // completely blank
  }

  // If description is empty and we don't have date or amount is zero, it's invalid
  if (!desc && (!hasDate || amtVal === 0)) {
    return true;
  }

  if (!desc) return true;

  // Repeated header rows check (common in paginated statement imports)
  const headerKeywords = [
    'description', 'narration', 'particulars', 'remarks', 'payee', 'vendor', 'details', 'particular',
    'date', 'txn date', 'txn_date', 'transaction date', 'value date', 'posted', 'tran date', 'val date',
    'amount', 'debit', 'credit', 'withdrawal', 'deposit', 'net amount', 'value', 'txn amount', 'balance',
    'posting date', 'debit amount', 'credit amount', 'running balance', 'instrument', 'category hint'
  ];
  if (headerKeywords.includes(desc)) {
    return true;
  }

  // Balance/metadata keywords that indicate non-transaction rows
  const startsWithKeywords = [
    'opening balance',
    'closing balance',
    'balance brought forward',
    'brought forward',
    'carried forward',
    'balance carried forward',
    'statement summary',
    'page total',
    'total credit',
    'total debit',
    'total',
    'totals',
    'subtotal'
  ];

  if (startsWithKeywords.some(k => {
    if (desc === k) return true;
    if (desc.startsWith(k + ' ') || desc.startsWith(k + ':')) {
      if (k === 'total' || k === 'totals' || k === 'subtotal') {
        return desc.length < 25;
      }
      return true;
    }
    return false;
  })) {
    return true;
  }

  if (desc.includes('generated by')) {
    return true;
  }

  return false;
}

/**
 * Filters out metadata, header, and balance rows from the given transaction list.
 */
export function getCleanTransactions(transactions: any[]): any[] {
  if (!transactions) return [];
  return transactions.filter(tx => !isMetadataTransaction(tx));
}
